### ISSUE TITLE
Cannot read property 'getContent' of null

### ISSUE THREAD

**Issue by grantCHG** [cupools/fis3-spriter-emilia#1]
安装完配置好fis文件后，fis3 release报错： Cannot read property 'getContent' of null

**Comment by cupools** [comment]
方便提供 fis 的配置文件吗，`'getContent' of null` 是插件从 fis 构建资源中引用样式文件时抛出的异常，可能是插件处理路径的问题

**Comment by grantCHG** [comment]
完全复制文档的fis配置文件
fis.match('::package', {
    spriter: 'emilia'
});

fis.config.set('settings.spriter.emilia', {
    dest: './components/css/',
    output: './components/images/',
    prefix: 'sprite-',
    algorithm: 'binary-tree',
    padding: 10,
    unit: 'px',
    convert: 1,
    quiet: true
});

**Comment by cupools** [comment]
想问问目录结构是怎样的，类似

```
- project
    + buld
    - src
        - css
            - foo.css 
        + images
        + views
    - fis-config.js
    - package.json
```

或者如果能提供重现问题的完整示例到 [Gist](http://gist.github.com/) 就最好了 :)

**Comment by grantCHG** [comment]
gist访问不了，估计要翻墙。
我放到github上https://github.com/a521000362/fis3-demo

**Comment by cupools** [comment]
我这边尝试了下没发现有问题哦。。

```
node => v4.4.0
fis3 => v3.4.17
fis3-spriter-emilia => v0.0.2
```

等会吃完饭试试 windows 平台。。
然后图标显示的问题是由于 icon 容器没有声明宽高，所以背景图就全都暴露出来了。声明宽高或者 `?__inline` 内联就可以了

![2016-07-17 12 03 07](https://cloud.githubusercontent.com/assets/5516312/16898686/8e23eff0-4c16-11e6-8559-29d9a5a7c05a.png)

**Comment by cupools** [comment]
在 win10 重现了。有两个问题，一个是插件中路径反斜杠没处理好，导致了 `getContent of null`；一个是 `child_process.execFileSync` 抛异常，原因不明，今晚有空会继续跟进。感谢反馈~ 

加班先 😢
